DROP DATABASE IF EXISTS knickipedia;
CREATE DATABASE knickipedia;

\c knickipedia;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  password VARCHAR NOT NULL
 );

CREATE TABLE articles (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  content TEXT,
  user_id INTEGER REFERENCES USERS(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_edit  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);